### ISSUE TITLE
Crash with "broken pipe"

### ISSUE THREAD

**Issue by larsmans** [felipec/git-remote-hg#10]
While trying to pull changes into a clone of the CPython repo with `git fetch origin`, I got the following crash:

```
searching for changes
no changes found
fatal: mark :289218 not declared
fast-import: dumping crash report to .git/fast_import_crash_17220
fatal: Error while running fast-import
Traceback (most recent call last):
  File "/home/larsb/bin/git-remote-hg", line 1322, in <module>
    sys.exit(main(sys.argv))
  File "/home/larsb/bin/git-remote-hg", line 1306, in main
    do_import(parser)
  File "/home/larsb/bin/git-remote-hg", line 721, in do_import
    export_branch(repo, branch)
  File "/home/larsb/bin/git-remote-hg", line 613, in export_branch
    export_ref(repo, branch, 'branches', head)
  File "/home/larsb/bin/git-remote-hg", line 547, in export_ref
    modified_final = export_files(c.filectx(f) for f in modified)
  File "/home/larsb/bin/git-remote-hg", line 288, in export_files
    print d
IOError: [Errno 32] Broken pipe
```

Crash report `fast_import_crash_17220` reads:

    fast-import crash report:
        fast-import process: 17220
        parent process     : 17219
        at Mon Aug 4 20:23:06 2014
    
    fatal: mark :289218 not declared
    
    Most Recent Commands Before Crash
    ---------------------------------
      feature done
      feature import-marks=.git/hg/origin/marks-git
      feature export-marks=.git/hg/origin/marks-git
      feature force
      blob
      mark :289220
      data 196121
      commit refs/hg/origin/branches/default
      mark :289221
      author Tal Einat <taleinat@gmail.com> 1405518740 +0300
      committer Tal Einat <taleinat@gmail.com> 1405518740 +0300
      data 66
    * from :289218
    
    Active Branch LRU
    -----------------
        active_branches = 0 cur, 5 max
    
      pos  clock name
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    
    Inactive Branches
    -----------------
    refs/hg/origin/branches/default:
      status      : dirty
      tip commit  : 0000000000000000000000000000000000000000
      old tree    : 0000000000000000000000000000000000000000
      cur tree    : 0000000000000000000000000000000000000000
      commit clock: 0
      last pack   : 
    
    
    Marks
    -----
      exported to .git/hg/origin/marks-git
    
    -------------------
    END OF CRASH REPORT

`git-remote-hg` version is 185852eac44c25ae2e8d3b3fb6c9630e754e6363.

**Comment by apeyser** [comment]
@fgb: I think the issue may be git prune. It's not the normal garbage collection cycle, but the few that remove long unreferenced objects. You won't see them often -- you'll only see them when you force a prune, or when the prunable objects finally expire, which means this should only be seen on the order of months

**Comment by nengxu** [comment]
Today encountered the same kind of error as @larsmans :

<code>
Traceback (most recent call last):
  File "/usr/bin/git-remote-hg", line 1322, in <module>
    sys.exit(main(sys.argv))
  File "/usr/bin/git-remote-hg", line 1306, in main
    do_import(parser)
  File "/usr/bin/git-remote-hg", line 721, in do_import
    export_branch(repo, branch)
  File "/usr/bin/git-remote-hg", line 613, in export_branch
    export_ref(repo, branch, 'branches', head)
  File "/usr/bin/git-remote-hg", line 557, in export_ref
    print "from :%s" % (rev_to_mark(parents[0]))
  File "/usr/bin/git-remote-hg", line 440, in rev_to_mark
    return marks.from_rev(rev.hex())
  File "/usr/bin/git-remote-hg", line 173, in from_rev
    return self.marks[rev]
KeyError: 'dc419a7899b22cf06cd1a60ee0ed3d0021fb45fb'
fatal: stream ends early
fast-import: dumping crash report to .git/fast_import_crash_7609
fatal: Error while running fast-import
<code>

**Comment by nengxu** [comment]
@fgb @g2p I fixed the above "fatal: stream ends early" error by removing the content of the "tips" hash. So this step is still needed in this kind of errors.

**Comment by fgb** [comment]
@Lekensteyn: What do you mean there's no way to reproduce the issue? I detail just a way to do so in my https://github.com/felipec/git-remote-hg/issues/10#issuecomment-67041815 to @fingolfin. There are different triggers for the broken pipe issue that I don't quite understand yet, though, but that can be fixed following the same steps.

@apeyser: Except that this is not on the git side. The only way I found to systematically trigger a broken pipe is to strip the tip commit in hg, as I detail above, which immediately causes the broken pipe. One reason I bump into this issue only sporadically is that I strip a commit from hg on the order of weeks / months.

@nengxu: I bumped into the same issue a month or so ago and ended up adding back the removal of the "tips" contents at the end of step 2 in https://github.com/felipec/git-remote-hg/issues/4#issuecomment-54333381.

**Comment by Lekensteyn** [comment]
@fgb AFAIK my affected repo did not have stripped commits (or else I need to ask my team members), so I thought there is some other issue. If a reproducer for actions other than stripping could be found, it could give some insight.

**Comment by felipec** [comment]
There are different issues at hand. For the one regarding the missing commits, that's an issue of Git's core. I have the patches that fix the problem. I also found a way to reproduce the issues that happen after that: missing marks, specially for the last_note: issue #56.
