### ISSUE TITLE
Branching does not work as expected?

### ISSUE THREAD

**Issue by tribut** [felipec/git-remote-hg#11]
Trying `git-remote-hg` for the first time, I was not able to create a branch that was not totally disjoint from its ancestor.

Here is what I tried:

```
git checkout -b branches/newbranch hgremote/branches/default
# do some changes
git commit
git push hgremote branches/newbranch
```

This did create a new branch, but it had nothing in common with `branches/default` (probably because all the commits were rewritten as if they had always been on that branch?).
Was I doing something wrong? I was trying to create pull requests, see `vcpromptignore` and `tailing-null` from [this repository](https://bitbucket.org/tribut/vcprompt/branches). The other branches were created using `hg` itself.

I am using git-remote-hg 185852eac44c25ae2e8d3b3fb6c9630e754e6363 from this repository and `git 1.9.1`/`hg 2.8.2` from Ubuntu trusty, none of the `.gitconfig` options are set.

**Comment by fingolfin** [comment]
Never mind, this problem with vcprompt seems to be specific to vcprompt. I tried with some other random public hg repository:
```
$ git clone hg-dbg::https://bitbucket.org/durin42/blatter
Cloning into 'blatter'...
requesting all changes
adding changesets
adding manifests
adding file changes
added 18 changesets with 25 changes to 7 files
Checking connectivity... done.
$ cd blatter
$ git push
searching for changes
no changes found
Everything up-to-date
$ git checkout -b branches/newbranch
Switched to a new branch 'branches/newbranch'
$ echo a > README
$ git commit -m a README
[branches/newbranch 8ab25bb] a
 1 file changed, 1 insertion(+), 197 deletions(-)
 rewrite README (100%)
$ git push --dry-run origin branches/newbranch
searching for changes
no changes found
To hg-dbg::https://bitbucket.org/durin42/blatter
 * [new branch]      branches/newbranch -> branches/newbranch
```
Inspecting the internals, it seems the branch was created the right way:
```
$ cd .git/hg
$ hg branches
newbranch                     18:0154ceea551e
default                       17:2e6d60d7d1d5 (inactive)
$ hg log | head -10
changeset:   18:0154ceea551e
branch:      newbranch
tag:         tip
user:        Max Horn <max@quendi.de>
date:        Fri Jan 30 18:43:43 2015 +0100
summary:     a

changeset:   17:2e6d60d7d1d5
user:        Augie Fackler <durin42@gmail.com>
date:        Sat Jul 31 16:46:30 2010 -0500
```
So, in other words: I can't reproduce the issue.

**Comment by felipec** [comment]
Sorry for the long delay. Have you tried pushing first the original branch? It should be a no-op.

**Comment by felipec** [comment]
Well. No reply.
