### ISSUE TITLE
TypeError: expected string or Unicode object, NoneType found

### ISSUE THREAD

**Issue by elektito** [felipec/git-remote-hg#32]
I have an empty mercurial repository that I want to add as a remote to a current git repo and push to, but when I run `git push origin master` I get the following error:

```
searching for changes
no changes found
searching for changes
Traceback (most recent call last):
File "/home/mostafa/bin/git-remote-hg", line 1330, in <module>
    sys.exit(main(sys.argv))
File "/home/mostafa/bin/git-remote-hg", line 1316, in main
    do_export(parser)
File "/home/mostafa/bin/git-remote-hg", line 1193, in do_export
    if not push(parser.repo, peer, parsed_refs, p_revs):
File "/home/mostafa/bin/git-remote-hg", line 1079, in push
    ret = push_unsafe(repo, remote, parsed_refs, p_revs)
File "/home/mostafa/bin/git-remote-hg", line 1048, in push_unsafe
    cg = repo.getbundle('push', heads=list(p_revs), common=common)
File "/usr/lib/python2.7/dist-packages/mercurial/localrepo.py", line 2021, in getbundle
    discovery.outgoing(cl, common, heads))
File "/usr/lib/python2.7/dist-packages/mercurial/localrepo.py", line 1996, in getlocalbundle
    if not outgoing.missing:
File "/usr/lib/python2.7/dist-packages/mercurial/util.py", line 277, in __get__
    result = self.func(obj)
File "/usr/lib/python2.7/dist-packages/mercurial/discovery.py", line 87, in missing
    self._computecommonmissing()
File "/usr/lib/python2.7/dist-packages/mercurial/discovery.py", line 75, in _computecommonmissing
    self.missingheads)
File "/usr/lib/python2.7/dist-packages/mercurial/revlog.py", line 401, in findcommonmissing
    heads = [self.rev(n) for n in heads]
File "/usr/lib/python2.7/dist-packages/mercurial/changelog.py", line 184, in rev
    r = super(changelog, self).rev(node)
File "/usr/lib/python2.7/dist-packages/mercurial/revlog.py", line 298, in rev
    return self._nodecache[node]
TypeError: expected string or Unicode object, NoneType found
```

(The line numbers in the traceback may not be very accurate because I had added some print statements to the code).

I did a bit of poking around and found out that the `heads` argument passed on frame 5 of the above traceback is `None` because `p_revs` has a value of `{None: 'refs/heads/master'}`.

**Comment by fingolfin** [comment]
What version of Mercurial is that? and git? have you tried it with my fork of git-remote-hg, i.e. https://github.com/fingolfin/git-remote-hg/

**Comment by felipec** [comment]
@fingolfin Stop promoting your fork on every issue reported. Specially if you have no idea what changes exactly could possibly fix the issue.

**Comment by felipec** [comment]
Can you post a script that reproduces this issue?

**Comment by fingolfin** [comment]
@felipec I don't know why you make this comment here, as there is no comment here by me -- but perhaps there was one and you deleted it? Such an act of hubris sadly would fit right into your behavioral pattern :-(.

You left your project for almost two years, and people had to fend for themselves. So of course I told people to use my fork in cases where I knew that my fork fixed the issue. Considering that, it seems in fact very likely to me that there used to be a comment here by me, since I know this bug, debugged it, and fixed it in my repository.

It is sad that you are so full of yourself that when you are clueless, you extrapolate to others and think they are clueless as well. What a sad state, esp. since you are quite talented when it comes to writing code. Not so much when it comes to interacting with others, or seeing your own mistakes.

Well, have fun debugging this by yourself then, or alternatively bisecting my repository for the fix, and then as copying it without attribution, as with the fixes for Mercurial 3.2 compatibility.

**Comment by felipec** [comment]
@fingolfin No. Your comment made it clear that you had no idea what was wrong here. You just promoted your fork without any clue if it might actually help. Stop.

**Comment by felipec** [comment]
@fingolfin No. I haven't copied anything from your repository. The Mercurial 3.2 fixes are straightforward, I found them by bisecting the Mercurial changes that triggered the issues. Stop.

**Comment by fingolfin** [comment]
Since you chose to censor my comment, I cannot properly respond to that, as I don't know what it said *shrug*

**Comment by felipec** [comment]
It's right there. https://github.com/felipec/git-remote-hg/issues/32#issuecomment-219744912

**Comment by fingolfin** [comment]
Aha. And from that you deduced that I never knew what the fault might be. Of course. :-)

**Comment by felipec** [comment]
@fingolfin I did not deduced it: you had no idea what the fault might be, that's a fact. Now if you don't stop I'm going to remove all these useless comments.

**Comment by betzw** [comment]
Today I got the same issue :frowning_face: 
Is there any update on this?

**Comment by kkk333** [comment]
Hello Guys could anyone help..I am new to OpenCV...

import cv2
import time
import sys
import numpy as np

cascPath = sys.argv[0:]
faceCascade = cv2.CascadeClassifier(cascPath)

video_capture = cv2.VideoCapture(0)

while True:
    # Capture frame-by-frame
    ret, frame = video_capture.read()

    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

    faces = faceCascade.detectMultiScale(
        gray,
        scaleFactor=1.1,
        minNeighbors=5,
        minSize=(30, 30),
        flags=cv2.CV_HAAR_SCALE_IMAGE)

    # Draw a rectangle around the faces
    for (x, y, w, h) in faces:
        cv2.rectangle(frame, (x, y), (x+w, y+h), (0, 255, 0), 2)

    # Display the resulting frame
    cv2.imshow('Video', frame)

    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

# When everything is done, release the capture
video_capture.release()
cv2.destroyAllWindows()


Error which I am getting:

Traceback (most recent call last):
  File "C:/Users/Mudit/PycharmProjects/CNN/webcamcheck.py", line 7, in <module>
    faceCascade = cv2.CascadeClassifier(cascPath)
TypeError: bad argument type for built-in operation

Process finished with exit code 1

**Comment by felipec** [comment]
Still waiting on a way to reproduce this issue.

**Comment by felipec** [comment]
I believe this is due to the fact that we tried to push no changes. This should not happen in recent versions of Mercurial.

However, Mark did implement a fix for older versions, and I just pushed it (fa3484e08b0f3f3ed15893531632fb86e3858e19).
