### ISSUE TITLE
Syntax error: newline unexpected

### ISSUE THREAD

**Issue by lzamparo** [felipec/git-remote-hg#43]
Tried cloning from two different hg repos, and get the same error every time:

```
zamparol@iski0019:~/projects/mirnylab$ git clone "hg::http://selenic.com/repo/hello"
Cloning into 'hello'...
/home/zamparol/bin/git-remote-hg: 5: /home/zamparol/bin/git-remote-hg: Syntax error: newline unexpected
```

What's up with this?

**Comment by tboegi** [comment]
Does
od -c /home/zamparol/bin/git-remote-hg
give some information ?

**Comment by lzamparo** [comment]
What are you expecting?  

```
od -c /home/zamparol/bin/git-remote-hg
```

prints out each character in the file separated by a space.  I make it 1374013 characters if I'm interpreting the output correctly.  Here's a sample:

```
1373500   y   n   c   =   "   a   s   y   n   c   "       c   r   o   s
1373520   s   o   r   i   g   i   n   =   "   a   n   o   n   y   m   o
1373540   u   s   "       s   r   c   =   "   h   t   t   p   s   :   /
1373560   /   a   s   s   e   t   s   -   c   d   n   .   g   i   t   h
1373600   u   b   .   c   o   m   /   a   s   s   e   t   s   /   g   i
1373620   t   h   u   b   /   i   n   d   e   x   -   9   a   3   6   8
1373640   3   c   4   1   d   6   6   3   9   f   4   b   3   9   4   6
1373660   c   1   4   f   e   1   c   1   e   8   0   6   5   d   d   c
1373700   4   4   f   0   c   e   c   d   b   0   b   7   8   9   9   9
1373720   4   6   e   6   e   3   3   2   c   e   b   .   j   s   "   >
1373740   <   /   s   c   r   i   p   t   >  \n
1373760  \n                          \n           <   /   b   o   d   y
1374000   >  \n   <   /   h   t   m   l   >  \n  \n
```

**Comment by lzamparo** [comment]
Here's the offending block, as reported by `od -c git-remote-hg | head -n 5`:

```
zamparol@iski0019:~/bin$ od -c git-remote-hg | head -n 5
0000000   <   !   D   O   C   T   Y   P   E       h   t   m   l   >  \n
0000020   <   h   t   m   l       l   a   n   g   =   "   e   n   "
0000040   c   l   a   s   s   =   "   "   >  \n           <   h   e   a
0000060   d       p   r   e   f   i   x   =   "   o   g   :       h   t
0000100   t   p   :   /   /   o   g   p   .   m   e   /   n   s   #
```

**Comment by tboegi** [comment]
It looks as if the content of your git-remote-hg file is not what it should be:
The first line looks completely wrong ("<DOCTYPE html..."

Could you check that file ? (mine looks like this:)


0000000   #   !   /   u   s   r   /   b   i   n   /   e   n   v       p
0000020   y   t   h   o   n   2  \n   #  \n   #       C   o   p   y   r
0000040   i   g   h   t       (   c   )       2   0   1   2       F   e
0000060   l   i   p   e       C   o   n   t   r   e   r   a   s  \n   #
0000100  \n  \n   #       I   n   s   p   i   r   e   d       b   y

**Comment by fingolfin** [comment]
@lzamparo Please reply, and either close this issue, or update with more information.

**Comment by lzamparo** [comment]
Sorry for the dropped line; @tboegi was correct, the content of my git-remote-hg was not as it should have been.  Ok to close
