### ISSUE TITLE
json import failure

### ISSUE THREAD

**Issue by ugorenner** [felipec/git-remote-hg#51]
When starting a clone without "json" python module (I use simplejson), I got the following error :

> git clone "hg::ssh://<....>" profile.git
> Cloning into 'profile.git'...
> Traceback (most recent call last):
>   File "/usr/bin/git-remote-hg", line 23, in <module>
>     import json
> ImportError: No module named json

**Comment by felipec** [comment]
What version of Python? From what I can see the json module is distributed with Python.

**Comment by ugorenner** [comment]
I use an old version : python 2.5

**Comment by felipec** [comment]
I see. Well, yeah, the json module is a requirement.

**Comment by felipec** [comment]
Almost everyone is using Python 2.7 now.
