### ISSUE TITLE
git fsck on cloned repo shows "warning in tree ad82bbbe50a28ff5e712c1a18986908168afbf10: contains '.git'"

### ISSUE THREAD

**Issue by mcepl** [felipec/git-remote-hg#53]
Reproduction steps are trivial (at least here with git 1.8.3.1 and hg 2.6.2):
1. git clone hg::https://bitbucket.org/fbennett/citeproc-js
2. cd citeproc-js
3. git fsck

The result is:

```
$ git fsck
Checking object directories: 100% (256/256), done.
warning in tree ad82bbbe50a28ff5e712c1a18986908168afbf10: contains '.git'
Checking objects: 100% (46524/46524), done.
$
```

Unfortunately, this seems to break my ability to push the created repository to GitLab.

**Comment by felipec** [comment]
Apparently somebody committed a .git directory in `a65687ba (Copy in current locales)`, and immediately removed it afterwards. I think the best you can do is use `git filter-branch` to filter those files.

This seems to be an issue specific to GitLab.
