### ISSUE TITLE
Issue #72 is ok when using solution below, already mentionend by  another user.

### ISSUE THREAD

**Issue by lvandenb** [felipec/git-remote-hg#76]
Solution for me was; like 
====
I just added:

if hasattr(a, 'rev'):
    a = a.rev()
    b = b.rev()

To the getrange function to check if there is a rev attribute/function that it can call. I am not 100% sure what was getting passed before or if that is sufficient to guard calling the rev method.
====

**Comment by mnauw** [comment]
As mentioned in #72, these issues are due to changes in recent Mercurial's internal API.  They have also been reported as issues in this [fork](https://github.com/mnauw/git-remote-hg) and are already fixed there (along with many other ones), see also generally #69.

**Comment by felipec** [comment]
As mentioned in #72 the fix is commit 00e95fd8df745db297eab035b31af8a518627bb1 which is released in v0.4.
