### ISSUE TITLE
How can i get more debug information?

### ISSUE THREAD

**Issue by scvRdy** [felipec/git-remote-hg#84]
Is it possible to get more information on this error?

after I do "git clone --mirror hg::....."

I get cloning into bare repository '...'
ERROR: Repository error.

**Comment by felipec** [comment]
Yes, there is one way to get debugging information using git's remote-helper:

    export GIT_TRANSPORT_HELPER_DEBUG=1

That should give you some idea of where the problem is. If you need more information please reopen this.
