### ISSUE TITLE
Extra lines in commit comment changes the commit hash - breaks hg-git interoperability

### ISSUE THREAD

**Issue by drandreasdr** [felipec/git-remote-hg#87]
Hi!

I just converted a Mercurial repo to git via git-remote-hg, and I get different commit hashes compared to the last time I converted the repo, 1-2 years ago.

- The git hashes are identical for the first hundred commits or so.
- Then, at one point, git-remote-hg apparently introduces a few extra lines in the commit comment (prefixed by `--HG--`). This makes the commit hash different for that particular commit.
- Every commit after that point now differs (understandably, since hashes are generated based on information in the parent commit)
- This obviously breaks inoperability, and is a serious blocker for my work.

Comparison of `git log` output for the converted repo, for the repo converted a few years ago (left) and the one converted today (right):
![image](https://user-images.githubusercontent.com/6980975/167253209-b8ff6144-413d-4f30-a907-6d284fcce1e3.png)

The original mercurial commit looks like this:
![image](https://user-images.githubusercontent.com/6980975/167253383-e1baa20d-71c4-4412-8596-9c7b7d5a5bd3.png)
(where I hope you'll excuse me obscuring some sensitive information)

I can see in the git-remote-hg source code when and why this extra text in the comment (prefixed by `--HG--`) is added. But I'm puzzled as to why this text is absent in the git repo that I converted a few years ago, and present in the one I converted today.

Do you know of any setting, configuration, or version discrepancy that could explain this difference? Do you have any recommendations for how I could achieve a one-to-one hg->git conversion such that I can preserve interoperability?

Best Regards,
Andreas

**Comment by drandreasdr** [comment]
Ah, I just figured it out. This setting in my ~/.gitconfig was causing the problem:

```
[remote-hg]
hg-git-compat = true
```

Setting it to false solved the problem.

**Comment by felipec** [comment]
@drandreasdr Yes, you probably converted it initially with `hg-git`.
