### ISSUE TITLE
question: What is a good workflow to prevent some(git specific) files from getting added to 

### ISSUE THREAD

**Issue by jck** [felipec/git-remote-hg#9]
I want to use git to work on a project(hosted on bitbucket hg) and periodically send pull requests upstream.

I have a bitbucket fork of that project and I'm using git-remote-hg to push changes to a particular branch to my fork and create pull requests. However, I need to delete git/github specific files such as .gitignore and .travis.yml every time I merge another branch into the branch tracking the hg remote.

Are there alternative/simpler ways of achieving this?

**Comment by fingolfin** [comment]
That's a very subjective question, I don't think this can be "resolved".... Here are the only things regarding this I can think of for now:
* Do not add a .gitignore in the first place. Instead add / edit .git/info/exclude in your clone (see [gitignore](http://git-scm.com/docs/gitignore) docs). Of course this may not be an option for .travis.yml, if you need / want to use Travis...
* Convince upstream to carry the .gitignore / .travis.yml files in their repo. They are not big or intrusive, after all.
* If you must keep the .travis.yml and can't convince upstream to add it, you can at least write a script which automates the creation of a "cleaned up" branch for you. I.e. which takes a branch, then uses [git filter-branch](http://git-scm.com/docs/git-filter-branch) to remove the offending files and commits adding them... Something like this snippet (potentially dangerous, use with care!):
```shell
git checkout -b name-of-clean-branch
git filter-branch --index-filter 'git rm --cached --ignore-unmatch .travis.yml .gitignore' \
                  --prune-empty name-of-clean-branch
```

**Comment by felipec** [comment]
Why not have two branches? The main branch doesn't have the files, and that's where you merge all your other branches to. And then have a separate branch with the files, and you merge your main branch to it.

**Comment by felipec** [comment]
I think this question has been answered.
