### ISSUE TITLE
SyntaxWaring: invalid escape sequence \w

### ISSUE THREAD

**Issue by till** [felipec/git-remote-hg#97]
Commands like `git clone` or `git remote show` yield:

```
/usr/local/bin/git-remote-hg:76: SyntaxWarning: invalid escape sequence '\w'
  RAW_AUTHOR_RE = re.compile('^(\w+) (?:(.+)? )?<(.*)> (\d+) ([+-]\d+)')
/usr/local/bin/git-remote-hg:281: SyntaxWarning: invalid escape sequence '\('
  m = re.match('^(.+?) ext:\((.+)\)$', name)
```

I suspect the regex is off. Or syntax needs to be updated?

The hg repo I am cloning: https://humungus.tedunangst.com/r/honk — not sure if related.

Operation seems to work though ultimately.

**Comment by felipec** [comment]
This is the same as issue #94 which is already fixed in 79e7599.
